[project]
name = "fastapi-bootstrap"
version = "0.1.0"
description = "A bootstrapped fastapi project, prioritizing clean architecture, testing, and easy deployment."
authors = [
    {name = "Michael VanDyke",email = "me@mjvandyke.com"}
]
license = {text = "MIT"}
readme = "README.md"
requires-python = ">=3.11,<4.0"
dependencies = [
]


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.group.dev.dependencies]
ruff = "^0.11.12"

