version: 0
Resources:
  - TargetService:
      Type: AWS::ECS::Service
      Properties:
        TaskDefinition: <TASK_DEFINITION>
        LoadBalancerInfo:
          ContainerName: fastapi-bootstrap-v1
          ContainerPort: 8000
        PlatformVersion: LATEST
Hooks:
  - BeforeInstall: arn:aws:lambda:us-east-1:ACCOUNT_ID:function:fastapi-bootstrap-validate-before-install-dev
  - AfterInstall: arn:aws:lambda:us-east-1:ACCOUNT_ID:function:fastapi-bootstrap-validate-deployment-dev
  - AfterAllowTestTraffic: arn:aws:lambda:us-east-1:ACCOUNT_ID:function:fastapi-bootstrap-validate-test-traffic-dev
  - BeforeAllowTraffic: arn:aws:lambda:us-east-1:ACCOUNT_ID:function:fastapi-bootstrap-run-migrations-dev
  - AfterAllowTraffic: arn:aws:lambda:us-east-1:ACCOUNT_ID:function:fastapi-bootstrap-validate-production-dev
