version: 0.0

Resources:
  - TargetService:
      Type: AWS::ECS::Service
      Properties:
        TaskDefinition: <TASK_DEFINITION>
        LoadBalancerInfo:
          ContainerName: "fastapi-bootstrap-v1"
          ContainerPort: 8000
        PlatformVersion: "LATEST"
        NetworkConfiguration:
          AwsvpcConfiguration:
            Subnets: ["<SUBNET_1>", "<SUBNET_2>"]
            SecurityGroups: ["<SECURITY_GROUP>"]
            AssignPublicIp: "DISABLED"

Hooks:
  - BeforeInstall: "arn:aws:lambda:us-east-1:ACCOUNT_ID:function:fastapi-bootstrap-validate-before-install-prod"
  - AfterInstall: "arn:aws:lambda:us-east-1:ACCOUNT_ID:function:fastapi-bootstrap-validate-deployment-prod"
  - AfterAllowTestTraffic: "arn:aws:lambda:us-east-1:ACCOUNT_ID:function:fastapi-bootstrap-validate-test-traffic-prod"
  - BeforeAllowTraffic: "arn:aws:lambda:us-east-1:ACCOUNT_ID:function:fastapi-bootstrap-run-migrations-prod"
  - AfterAllowTraffic: "arn:aws:lambda:us-east-1:ACCOUNT_ID:function:fastapi-bootstrap-validate-production-prod"
