AWSTemplateFormatVersion: '2010-09-09'

Description: "FastAPI Bootstrap Deployment for Production Environment"

Resources:
  TargetService:
    Type: AWS::ECS::Service
    Properties:
      TaskDefinition: <TASK_DEFINITION>
      LoadBalancers:
        - ContainerName: "fastapi-bootstrap-v1"
          ContainerPort: 8000
      PlatformVersion: "LATEST"

Hooks:
  - BeforeInstall: "arn:aws:lambda:us-east-1:ACCOUNT_ID:function:fastapi-bootstrap-validate-before-install-prod"
  - AfterInstall: "arn:aws:lambda:us-east-1:ACCOUNT_ID:function:fastapi-bootstrap-validate-deployment-prod"
  - AfterAllowTestTraffic: "arn:aws:lambda:us-east-1:ACCOUNT_ID:function:fastapi-bootstrap-validate-test-traffic-prod"
  - BeforeAllowTraffic: "arn:aws:lambda:us-east-1:ACCOUNT_ID:function:fastapi-bootstrap-run-migrations-prod"
  - AfterAllowTraffic: "arn:aws:lambda:us-east-1:ACCOUNT_ID:function:fastapi-bootstrap-validate-production-prod"
