# yaml-language-server: $schema=https://raw.githubusercontent.com/SchemaStore/schemastore/master/src/schemas/json/github-workflow.json
name: Code Quality and Tests

on: [push]

permissions:
  contents: read

jobs:
  quality:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.11
      uses: actions/setup-python@v3
      with:
        python-version: '3.11'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install poetry
        poetry install
    - name: Lint with Ruff
      run: |
        poetry run poe lint
    - name: Check Common Mispellings
      run: |
        poetry run poe spellcheck
    - name: Run unit tests
      run: |
        poetry run poe unittest
